/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jclient;

import java.awt.Color;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.util.ArrayList;

/**
 *
 * @author LS_Fisso
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    public ClientFrame() {
        initComponents();
        addContact("broadCast");

        addContact("Matteo");

        getRoom("broadCast").addMessage(getMessageIN("Ciao come ti va?"), "in");
        getRoom("broadCast").addMessage(getMessageOut("Bene e tu?"), "out");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPaneContact = new javax.swing.JScrollPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jScrollPaneMessage = new javax.swing.JScrollPane();
        jPanelMessageSend = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaMessageSend = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat");

        jSplitPane1.setDividerLocation(230);
        jSplitPane1.setDividerSize(4);

        jScrollPaneContact.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jSplitPane1.setLeftComponent(jScrollPaneContact);

        jSplitPane3.setDividerLocation(410);
        jSplitPane3.setDividerSize(3);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPaneMessage.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneMessage.setToolTipText("");
        jScrollPaneMessage.setMinimumSize(new java.awt.Dimension(23, 100));
        jSplitPane3.setTopComponent(jScrollPaneMessage);

        jScrollPane4.setEnabled(false);

        jTextAreaMessageSend.setEditable(false);
        jTextAreaMessageSend.setColumns(20);
        jTextAreaMessageSend.setRows(1);
        jTextAreaMessageSend.setEnabled(false);
        jTextAreaMessageSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaMessageSendKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(jTextAreaMessageSend);

        jButtonSend.setText("Send");
        jButtonSend.setEnabled(false);
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMessageSendLayout = new javax.swing.GroupLayout(jPanelMessageSend);
        jPanelMessageSend.setLayout(jPanelMessageSendLayout);
        jPanelMessageSendLayout.setHorizontalGroup(
            jPanelMessageSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMessageSendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSend)
                .addContainerGap())
        );
        jPanelMessageSendLayout.setVerticalGroup(
            jPanelMessageSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMessageSendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMessageSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMessageSendLayout.createSequentialGroup()
                        .addComponent(jButtonSend)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        jSplitPane3.setRightComponent(jPanelMessageSend);

        jSplitPane1.setBottomComponent(jSplitPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:

        currentChatRoom.addMessage(getMessageOut(jTextAreaMessageSend.getText()), "out");
        jTextAreaMessageSend.setText("");
        printMessageList(currentChatRoom);

        //add network part

    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jTextAreaMessageSendKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaMessageSendKeyTyped
        if (jTextAreaMessageSend.getText().length() > 1) {
            jButtonSend.setEnabled(true);
        } else {
            if (jTextAreaMessageSend.getText().isEmpty()) {
                jButtonSend.setEnabled(evt.getKeyChar() != 8);
            } else {
                jButtonSend.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jTextAreaMessageSendKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    private void printMessageList(ChatRoom room) {
        room.getContactBar().setBackground(Color.gray);
        if (currentChatRoom != null) {
            currentChatRoom.getContactBar().setBackground(Color.lightGray);
        }
        currentChatRoom = room;

        JPanel jPanelMessaggeList = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanelMessaggeListLayout = new javax.swing.GroupLayout(jPanelMessaggeList);

        jPanelMessaggeList.setLayout(jPanelMessaggeListLayout);
        GroupLayout.ParallelGroup HParallelGroup = jPanelMessaggeListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        GroupLayout.SequentialGroup VSequentialGroup = jPanelMessaggeListLayout.createSequentialGroup();

        for (Object[] objects : room.getMessagge()) {
            if (((String) objects[1]).equals("in")) {
                HParallelGroup.addComponent(((JPanel) objects[0]), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
                VSequentialGroup.addComponent(((JPanel) objects[0]), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            }
            if (((String) objects[1]).equals("out")) {
                HParallelGroup.addComponent(((JPanel) objects[0]), javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
                VSequentialGroup.addComponent(((JPanel) objects[0]), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            }
        }

        jPanelMessaggeListLayout.setHorizontalGroup(HParallelGroup);
        jPanelMessaggeListLayout.setVerticalGroup(
                jPanelMessaggeListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VSequentialGroup)
        );

        jScrollPaneMessage.setViewportView(jPanelMessaggeList);

    }

    private JPanel getMessageOut(String text) {
        int maxLenght = 30;
        if (text.length() > maxLenght) { //if the string is too long
            
            
            String[] s = text.split("\n");
            text = "";
            for (String l : s) {
                if (l.length() > maxLenght) {
                    String[] ls = l.split(" ");

                    String nl = "";
                    int le = 0;

                    for (String w : ls) {
                        if (w.length() > maxLenght) {
                            String tmp = w.substring(0, maxLenght-1);
                            int last = maxLenght;
                            for (int j = maxLenght; j < w.length(); j++) {
                                if (j+1 == w.length() || (j + 1) % maxLenght == 0) {
                                    tmp += '\n' + w.substring(last, j);
                                    last = j+1;
                                }
                            }
                            
                            le = 0;
                            nl += '\n' + tmp;
                            
                        } else {
                            if (le + w.length() <= maxLenght) {
                                nl += ' '+w;
                                le += w.length();
                            } else {
                                nl += '\n' + w;
                                le = 0;
                            }
                        }
                    }
                    text += '\n' + nl;
                }
            }
            
            //System.out.println("jclient.ClientFrame.getMessageOut(): "+text);
        }

        JPanel jPanelMessageOut = new javax.swing.JPanel();
        javax.swing.JTextArea jTextAreaMessageOut = new javax.swing.JTextArea();

        jTextAreaMessageOut.setEditable(false);
        jTextAreaMessageOut.setBackground(java.awt.SystemColor.inactiveCaption);
        jTextAreaMessageOut.setColumns(20);
        jTextAreaMessageOut.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextAreaMessageOut.setRows(5);
        jTextAreaMessageOut.setText(text);
        jTextAreaMessageOut.setToolTipText("");
        jTextAreaMessageOut.setWrapStyleWord(true);
        jTextAreaMessageOut.setAutoscrolls(false);

        javax.swing.GroupLayout jPanelMessageOutLayout = new javax.swing.GroupLayout(jPanelMessageOut);
        jPanelMessageOut.setLayout(jPanelMessageOutLayout);
        jPanelMessageOutLayout.setHorizontalGroup(
                jPanelMessageOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMessageOutLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextAreaMessageOut, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        jPanelMessageOutLayout.setVerticalGroup(
                jPanelMessageOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMessageOutLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextAreaMessageOut, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addContainerGap())
        );
        return jPanelMessageOut;
    }

    private JPanel getMessageIN(String text) {
        JPanel jPanelMessageInNEW = new javax.swing.JPanel();
        javax.swing.JTextArea jTextAreaMessageInNEW = new javax.swing.JTextArea();

        jTextAreaMessageInNEW.setEditable(false);
        jTextAreaMessageInNEW.setBackground(new java.awt.Color(140, 175, 150));
        jTextAreaMessageInNEW.setColumns(20);
        jTextAreaMessageInNEW.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextAreaMessageInNEW.setRows(5);
        jTextAreaMessageInNEW.setText(text);
        jTextAreaMessageInNEW.setToolTipText("");

        javax.swing.GroupLayout jPanelMessageInLayout = new javax.swing.GroupLayout(jPanelMessageInNEW);
        jPanelMessageInNEW.setLayout(jPanelMessageInLayout);
        jPanelMessageInLayout.setHorizontalGroup(jPanelMessageInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMessageInLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextAreaMessageInNEW, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanelMessageInLayout.setVerticalGroup(jPanelMessageInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMessageInLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextAreaMessageInNEW, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addContainerGap())
        );
        return jPanelMessageInNEW;
    }

    private void addContact(String name) {
        //contactList.add(getContactEl(name));
        contacts.add(new ChatRoom(name, getContactEl(name)));

        paneContact = new javax.swing.JPanel();

        paneContact.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout paneContactLayout = new javax.swing.GroupLayout(paneContact);

        paneContact.setLayout(paneContactLayout);

        GroupLayout.ParallelGroup HParallelGroup = paneContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);

        GroupLayout.SequentialGroup vSequentialGroup = paneContactLayout.createSequentialGroup();

        for (ChatRoom contact : contacts) {
            HParallelGroup.addGroup(paneContactLayout.createSequentialGroup()
                    .addComponent(contact.getContactBar(), javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)
            );

            vSequentialGroup.addComponent(contact.getContactBar(), javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE);
        }
        //vSequentialGroup.addContainerGap(389, Short.MAX_VALUE);

        paneContactLayout.setHorizontalGroup(HParallelGroup);

        paneContactLayout.setVerticalGroup(
                paneContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(vSequentialGroup)
        );

        jScrollPaneContact.setViewportView(paneContact);

    }

    private JPanel getContactEl(String text) {
        JPanel jPanelContactNEW = new javax.swing.JPanel();
        JLabel jLabelContactNEW = new javax.swing.JLabel();

        jPanelContactNEW.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelContactNEW.setBackground(Color.lightGray);

        jLabelContactNEW.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jLabelContactNEW.setText(text);

        javax.swing.GroupLayout jPanelContact2Layout = new javax.swing.GroupLayout(jPanelContactNEW);
        jPanelContactNEW.setLayout(jPanelContact2Layout);
        jPanelContact2Layout.setHorizontalGroup(jPanelContact2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelContact2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelContactNEW, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanelContact2Layout.setVerticalGroup(jPanelContact2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContact2Layout.createSequentialGroup()
                        .addComponent(jLabelContactNEW)
                        .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelContactNEW.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactClick(text);
            }
        });

        return jPanelContactNEW;
    }

    private void ContactClick(String contactName) {
        jTextAreaMessageSend.setEnabled(true);
        jTextAreaMessageSend.setEditable(true);

        printMessageList(getRoom(contactName));
    }

    private ChatRoom getRoom(String name) {
        for (ChatRoom contact : contacts) {
            if (contact.getName().equals(name)) {
                return contact;
            }
        }
        return null;
    }
    // private ArrayList<JPanel> contactList = new ArrayList<JPanel>();

    class ChatRoom {

        private JPanel contactBar;

        private String name;

        private ArrayList<Object[]> messagge;

        public ChatRoom(String name, JPanel contactBar) {
            this.name = name;
            this.contactBar = contactBar;
            messagge = new ArrayList<>();
        }

        public void addMessage(JPanel message, String type) {
            Object[] a = {message, type};
            messagge.add(a);
        }

        public String getName() {
            return name;
        }

        public ArrayList<Object[]> getMessagge() {
            return messagge;
        }

        public JPanel getContactBar() {
            return contactBar;
        }

        public void setContactBar(JPanel contactBar) {
            this.contactBar = contactBar;
        }

    }

    private ArrayList<ChatRoom> contacts = new ArrayList();

    private javax.swing.JPanel paneContact;

    private ChatRoom currentChatRoom;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSend;
    private javax.swing.JPanel jPanelMessageSend;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPaneContact;
    private javax.swing.JScrollPane jScrollPaneMessage;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTextArea jTextAreaMessageSend;
    // End of variables declaration//GEN-END:variables
}
